"""
db/dump_schema.py — print the AUTHORITATIVE live schema (every CREATE statement across the 7 SQLite DBs).

The single source of truth for the schema is the per-domain DDL in db/*.py (run by `init_all`). This tool
materializes a fresh, fully-initialised set of the seven DBs in a temp dir and dumps every table + index,
grouped by database. It is the reference that drives the eventual Phase-1 Postgres migration — and the
answer to "what is the real schema?" without trusting a hand-maintained parallel file (which drifts).

`db/schema.sql` is a FROZEN Phase-1 sketch + the RLS/permissions design; the table DDL there must be
regenerated from this output (translating types) before any migration.

    python -m db.dump_schema
"""
from __future__ import annotations

import tempfile
from typing import Dict, List

from db.paths import CamelDbs, init_all
from db.sqlite import connection

# the 7 domains, in dependency-friendly order
DB_ORDER = ["market", "macro", "fundamentals", "news", "sharia", "portfolio", "learning"]


def dump_schema(base_dir: str = None) -> Dict[str, List[str]]:
    """{db_name: [CREATE statements]} from a freshly-initialised set of the 7 DBs (tables then indexes)."""
    base = base_dir or tempfile.mkdtemp(prefix="camel_schema_")
    dbs = CamelDbs.from_dir(base)
    init_all(dbs)
    out: Dict[str, List[str]] = {}
    for name in DB_ORDER:
        with connection(getattr(dbs, name)) as conn:
            rows = conn.execute(
                "SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%' "
                "ORDER BY (type='index'), name").fetchall()      # tables first, then indexes; alpha within
        out[name] = [r[0] for r in rows]
    return out


def render(schema: Dict[str, List[str]]) -> str:
    lines: List[str] = ["-- AUTHORITATIVE live schema, generated by `python -m db.dump_schema`.",
                        "-- Source of truth: db/*.py. Do not edit this output by hand."]
    for name, stmts in schema.items():
        lines.append(f"\n-- ===== camel_{name}.db =====")
        lines += [s.strip().rstrip(";") + ";" for s in stmts]
    return "\n".join(lines)


def main(argv=None) -> int:                                      # pragma: no cover - CLI
    import sys
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    print(render(dump_schema()))
    return 0


if __name__ == "__main__":                                       # pragma: no cover
    raise SystemExit(main())
