-- =============================================================================
--  The Camel — Phase-1 Supabase / Postgres MIGRATION TARGET  (design + process)
-- =============================================================================
--
--  ⚠️  THIS FILE IS NOT THE SCHEMA.  The single source of truth for the schema is the
--      per-domain DDL in db/*.py (run by db.paths.init_all). An earlier hand-maintained
--      Postgres copy of every table lived here and DRIFTED ~16 sprints behind (it was
--      missing macro_observations, edge_reports, desk_runs, opportunity_proposals,
--      research_evidence, sanctions, sharia_status, the portfolio/learning tables, and
--      the point-in-time columns). Rather than re-drift, the table DDL has been removed.
--
--  This file now holds the two things that ARE durable design (not a table copy):
--    (1) the PROCESS to regenerate the Postgres DDL from the live schema, and
--    (2) the RLS / permissions model — the "second wall" that SQLite cannot enforce but
--        Postgres can, and which is the whole point of migrating.
--
-- -----------------------------------------------------------------------------
--  (1) Regenerate the Postgres DDL before migrating
-- -----------------------------------------------------------------------------
--  Dump the authoritative live schema:        python -m db.dump_schema
--  Then translate SQLite → Postgres types:
--      INTEGER PRIMARY KEY AUTOINCREMENT  →  bigint generated always as identity primary key
--      TEXT                               →  text
--      REAL                               →  numeric
--      INTEGER (used as a boolean flag)   →  boolean        (frozen, edge_allowed, decision, …)
--      TEXT timestamp (ISO-8601 UTC)      →  timestamptz
--      TEXT holding JSON                  →  jsonb          (steps_json, reason_chain, metrics, …)
--  Keep every UNIQUE(...) and the point-in-time columns (event_date/reported_at/ingested_at/
--  known_at) — they are what make backtests honest and MUST survive the migration.
--
-- -----------------------------------------------------------------------------
--  (2) RLS / permissions — the second wall (enforce with a dedicated 'camel' role)
-- -----------------------------------------------------------------------------
--  In Phase 0 the agent process is kept off the founder-owned config by OS file ACLs and a
--  config-immutability test. In Postgres, enforce the same invariants at the DB layer so the
--  agent role *structurally* cannot tamper — the constitution made un-bypassable by grants.
--
--      -- the ledger is append-only: the agent may INSERT, never UPDATE/DELETE (hash chain integrity)
--      alter table ledger enable row level security;
--      create policy camel_ledger_insert on ledger for insert to camel with check (true);
--      revoke update, delete on ledger from camel;
--
--      -- founder-owned limits/config are READ-ONLY to the agent (Constitution rule #7)
--      revoke insert, update, delete on config   from camel;
--      grant  select                  on config   to   camel;
--      revoke insert, update, delete on whitelist from camel;   -- Sharia gate is founder-owned
--      grant  select                  on whitelist to   camel;
--
--      -- approvals: the agent may REQUEST (insert pending), only a human DECIDES (update status)
--      revoke update on approvals from camel;
--
--      -- audit trails are append-only telemetry
--      revoke update, delete on guardrail_events, runs, edge_reports, desk_runs from camel;
--
--  Migrate to this when multi-device / remote dashboard / real capital makes DB-enforced
--  permissions worth the operational cost. Until then, db/*.py + init_all is the schema, and
--  the brain/window split already keeps the service-role key brain-side only.
